### ISSUE TITLE
What Are Some Reasons Not to Become a Programmer?  翻译复查问题

### ISSUE THREAD

**Issue by O0lele0O** [doobby/fireup#1]
- Of course, this could also be motivation for some people to become developers so they can one day manage them well.There is definitely a lot of room in the business world for good IT managers.

# 翻译
- 当然，这也可以成为一些人做程序员的的动力，他们可以把自己每天的工作安排的很好。优秀的IT经理会在商业世界中获得很多机会这是肯定的。

# 我的理解

- 当然，这也是部分人加入开发者而后可以更好管理编程者的动机。对于一个好的IT管理者确实在商业世界有很大的发挥空间。

**Comment by reborn1867** [comment]
前半部分确实不太对，不过There is a lot of room 一般理解为有足够的空缺，表达对优秀管理者的数量需求很大。
